opcion:
    pattern:  /
    defaults: { _controller: "PabloAdjWebBundle:Opcion:index" }
    
opcion_list_opciones_modulo:
    pattern:  /{moduloId}/listmodulos
    defaults: { _controller: "PabloAdjWebBundle:Opcion:listopcionesmodulo" }
    
opcion_list_atributos_opcion_json:
    pattern:  /{opcionId}/listatributosopcion.{_format}
    defaults: { _controller: "PabloAdjWebBundle:Opcion:listAtributosOpcionJson"}
    requirements: { _format: (xml|json), _method: GET }  
    
opcion_list_atributos_opcion:
    pattern:  /{opcionId}/listatributos
    defaults: { _controller: "PabloAdjWebBundle:Opcion:listAtributosOpcion"}
    
opcion_save_atributos_opcion_json:
    pattern:  /saveatributosopcion
    defaults: { _controller: "PabloAdjWebBundle:Opcion:saveAtributosOpcionJson", _format: (json)}
    requirements: {_format: (xml|json), _method: POST } 

opcion_show:
    pattern:  /{id}/show
    defaults: { _controller: "PabloAdjWebBundle:Opcion:show" }

opcion_new:
    pattern:  /new
    defaults: { _controller: "PabloAdjWebBundle:Opcion:new" }

opcion_create:
    pattern:  /create
    defaults: { _controller: "PabloAdjWebBundle:Opcion:create" }
    requirements: { _method: post }

opcion_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PabloAdjWebBundle:Opcion:edit" }

opcion_update:
    pattern:  /{id}/update
    defaults: { _controller: "PabloAdjWebBundle:Opcion:update" }
    requirements: { _method: post }

opcion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PabloAdjWebBundle:Opcion:delete" }
    requirements: { _method: post }
